# Generated by Django 5.0.4 on 2024-04-27 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deck_app', '0002_rename_deck_id_card_deck_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_revisao', models.DateTimeField(auto_created=True)),
                ('erros', models.IntegerField()),
                ('acertos', models.IntegerField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deck_app.deck')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
