# Generated by Django 5.0.4 on 2024-06-25 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_app', '0005_alter_deck_criado_em'),
        ('revisar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisao',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck_app.deck'),
        ),
    ]
