# Generated by Django 5.0.4 on 2024-04-27 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_created=True)),
                ('titulo', models.CharField(max_length=60)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('erros', models.IntegerField(default=0)),
                ('acertos', models.IntegerField(default=0)),
                ('desempenho_geral', models.FloatField(default=0.0)),
                ('ultima_revisao', models.DateTimeField()),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frente', models.CharField(max_length=400)),
                ('verso', models.CharField(max_length=400)),
                ('deck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck_app.deck')),
            ],
        ),
    ]
