# Generated by Django 5.0.4 on 2024-04-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='deck_id',
            new_name='deck',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
