# Generated by Django 5.0.4 on 2024-05-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_app', '0002_rename_deck_id_card_deck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='ultima_revisao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
