# Generated by Django 5.0.4 on 2024-05-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_app', '0003_alter_deck_ultima_revisao'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='num_cards',
            field=models.IntegerField(default=0),
        ),
    ]
