# Generated by Django 5.0.4 on 2024-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_app', '0004_deck_num_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
